# Un artículo de Infobae que no aparece en las búsquedas.

In [1]:
import pandas as pd
from gnews import GNews
gn = GNews()

## Este artículo existe

El título ahora es diferente.

Así fue detectado con el RSS de Google News.

Título:

GATILLO FÁCIL en LUGANO: confirman que el VECINO MURIÓ por un DISPARO de la POLICÍA - El Destape

Fecha de detección:

12/03/2026

URL real:

https://www.eldestapeweb.com/sociedad/policia-de-la-ciudad/confirman-que-el-vecino-de-lugano-fallecido-recibio-un-disparo-letal-20251227192952

Link google:

https://news.google.com/rss/articles/CBMi2gFBVV95cUxNVzY4VnlabDFEd2Q2TUZ4bVdEZVJFdGdwNktNUERvMFVxSUFpTDI1LUZ6UENQb0pXSk5LQU90VFlxalVrVXluZGJyQmhBVmxvUGR1MEN6YmV1M091aUtFTWFxSnNTRXdyUlk1Rmt3WWhBMlN2N2IyTzdRYjRkTWdsQ0NZVmZpMUVENFh2RWZISUdfdzNTYktlcFNaNGRhM0FrVk82MGU1Y181OFpfckJ0dDVBQXpfS1ltTm9IanE3M09yNW1RY3hGcEQ4a2xxTzBWOEt4eGI4eDRiZ9IB2gFBVV95cUxNVzY4VnlabDFEd2Q2TUZ4bVdEZVJFdGdwNktNUERvMFVxSUFpTDI1LUZ6UENQb0pXSk5LQU90VFlxalVrVXluZGJyQmhBVmxvUGR1MEN6YmV1M091aUtFTWFxSnNTRXdyUlk1Rmt3WWhBMlN2N2IyTzdRYjRkTWdsQ0NZVmZpMUVENFh2RWZISUdfdzNTYktlcFNaNGRhM0FrVk82MGU1Y181OFpfckJ0dDVBQXpfS1ltTm9IanE3M09yNW1RY3hGcEQ4a2xxTzBWOEt4eGI4eDRiZw?oc=5

## Búsquedas

In [2]:
# google_news.period = '7d'  # News from last 7 days
# google_news.max_results = 100  # number of responses across a keyword
gn.country = 'AR'  # News from a specific country 
gn.language = 'es'  # News in a specific language
# google_news.exclude_websites = ['zerodha.com', 'bbc.com']  # Exclude news from specific website i.e Yahoo.com and CNN.com
# google_news.start_date = (2026, 1, 1) # Search from 1st Jan 2026
# google_news.end_date = (2026, 3, 1) # Search until 1st March 2026
# google_news.end_date = (2026, 1, 2)

In [11]:
# articles = gn.get_news('GATILLO FÁCIL en LUGANO: confirman que el VECINO MURIÓ por un DISPARO de la POLICÍA')
articles_noAR = gn.get_news('Gatillo fácil Lugano')

In [12]:
len(articles_noAR)

45

In [14]:
df = pd.DataFrame(articles_noAR)
df

,title,description,published date,url,publisher
0,Procesamiento y prisión preventiva para el gat...,Procesamiento y prisión preventiva para el gat...,"Thu, 08 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMinAFBV...,"{'href': 'https://www.correpi.org', 'title': '..."
1,Gatillo fácil en Navidad en Villa Lugano: crec...,Gatillo fácil en Navidad en Villa Lugano: crec...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMizAFBV...,{'href': 'https://www.agenciapacourondo.com.ar...
2,Gatillo fácil en Lugano: “No es la primera vez...,Gatillo fácil en Lugano: “No es la primera vez...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi6wFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
3,Matar por matar: la violencia policial porteña...,Matar por matar: la violencia policial porteña...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiygFBV...,"{'href': 'https://lavaca.org', 'title': 'lavac..."
4,Caso de gatillo fácil en Lugano: un hombre mur...,Caso de gatillo fácil en Lugano: un hombre mur...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi6wFBV...,"{'href': 'https://www.filo.news', 'title': 'Fi..."
5,"Gatillo fácil en Lugano: familiares, organizac...","Gatillo fácil en Lugano: familiares, organizac...","Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMixAFBV...,"{'href': 'https://www.pagina12.com.ar', 'title..."
6,La reconstrucción de Mapa de la Policía que ex...,La reconstrucción de Mapa de la Policía que ex...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi0wFBV...,"{'href': 'https://www.eldiarioar.com', 'title'..."
7,Investigan un posible caso de gatillo fácil en...,Investigan un posible caso de gatillo fácil en...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMitgFBV...,"{'href': 'https://www.perfil.com', 'title': 'P..."
8,Navidad Trágica en Villa Lugano: la pobreza y ...,Navidad Trágica en Villa Lugano: la pobreza y ...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,"{'href': 'https://radiografica.org.ar', 'title..."
9,Pelea entre vecinos en Villa Lugano: intervino...,Pelea entre vecinos en Villa Lugano: intervino...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMinAFBV...,"{'href': 'https://www.clarin.com', 'title': 'C..."
10,"Gatillo fácil en Lugano, Juan Gabriel murió po...","Gatillo fácil en Lugano, Juan Gabriel murió po...","Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMikwFBV...,"{'href': 'https://www.anred.org', 'title': 'AN..."
11,La Policía de Macri fusiló a un vecino en plen...,La Policía de Macri fusiló a un vecino en plen...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMivgFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
12,Gatillo fácil en Lugano: Policía de la Ciudad ...,Gatillo fácil en Lugano: Policía de la Ciudad ...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...,"{'href': 'https://argentina.indymedia.org', 't..."
13,Navidad trágica y gatillo fácil: la Policía de...,Navidad trágica y gatillo fácil: la Policía de...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMizgFBV...,"{'href': 'https://www.pagina12.com.ar', 'title..."
14,El asesinato de Gabriel González confirma a la...,El asesinato de Gabriel González confirma a la...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMitwFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
15,"""Fue asesinado a quemarropa"": la historia del ...","""Fue asesinado a quemarropa"": la historia del ...","Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiyAFBV...,"{'href': 'https://www.eldiarioar.com', 'title'..."
16,"""Fuiste vos"": preventiva para el policía de la...","""Fuiste vos"": preventiva para el policía de la...","Fri, 09 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMitAFBV...,"{'href': 'https://www.clarin.com', 'title': 'C..."
17,Villa Lugano: un vecino fusilado en navidad po...,Villa Lugano: un vecino fusilado en navidad po...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMihwFBV...,"{'href': 'https://www.anred.org', 'title': 'AN..."
18,Denuncian un nuevo caso de gatillo fácil en la...,Denuncian un nuevo caso de gatillo fácil en la...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMimAFBV...,"{'href': 'https://www.pagina12.com.ar', 'title..."
19,Villa Lugano: la víctima murió por un disparo ...,Villa Lugano: la víctima murió por un disparo ...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMirwFBV...,"{'href': 'https://www.clarin.com', 'title': 'C..."
20,Lugano: denuncian que la Policía mató a un vec...,Lugano: denuncian que la Policía mató a un vec...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...,"{'href': 'https://noticias.perfil.com', 'title..."
21,Investigan la muerte de un hombre durante un o...,Investigan la muerte de un hombre durante un o...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiuwFBV...,"{'href': 'https://www.perfil.com', 'title': 'P..."
22,Procesaron con prisión preventiva a Gastón Miñ...,Procesaron con prisión preventiva a Gastón Miñ...,"Thu, 08 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMi3AFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
23,"Quién era Gabriel González, el hombre que habr...","Quién era Gabriel González, el hombre que habr...","Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi_wFBV...,"{'href': 'https://radiomitre.cienradios.com', ..."
24,Detuvieron a un policía de la Ciudad por el as...,Detuvieron a un policía de la Ciudad por el as...,"Wed, 31 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMirAFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
25,Lugano: la víctima murió por un disparo en el ...,Lugano: la víctima murió por un disparo en el ...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi2wFBV...,"{'href': 'https://www.perfil.com', 'title': 'P..."
26,Otro fusilamiento de la Policía de Macri a ple...,Otro fusilamiento de la Policía de Macri a ple...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMimgFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
27,Gatillo Fácil: procesaron con prisión preventi...,Gatillo Fácil: procesaron con prisión preventi...,"Fri, 09 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMiwAFBV...,"{'href': 'https://litigio.com.ar', 'title': 'L..."
28,Navidad violenta en Villa Lugano: denuncian qu...,Navidad violenta en Villa Lugano: denuncian qu...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiswFBV...,"{'href': 'https://www.minutouno.com', 'title':..."
29,Detuvieron al efectivo de la Policía de la Ciu...,Detuvieron al efectivo de la Policía de la Ciu...,"Wed, 31 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiywFBV...,"{'href': 'https://www.minutouno.com', 'title':..."
30,Gatillo fácil en Lugano: Magnetto y Clarín int...,Gatillo fácil en Lugano: Magnetto y Clarín int...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiogFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
31,Procesaron por homicidio agravado al policía d...,Procesaron por homicidio agravado al policía d...,"Thu, 08 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
32,Vecinos de Lugano marcharon por el joven traba...,Vecinos de Lugano marcharon por el joven traba...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiuwFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
33,Qué revela la determinante autopsia a Gabriel ...,Qué revela la determinante autopsia a Gabriel ...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiyAFBV...,"{'href': 'https://www.minutouno.com', 'title':..."
34,"Genio y figura: Juan Gabriel González, el fusi...","Genio y figura: Juan Gabriel González, el fusi...","Tue, 06 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMiowFBV...,"{'href': 'https://lavaca.org', 'title': 'lavac..."
35,"Gatillo fácil en Constitución: La causa, recar...","Gatillo fácil en Constitución: La causa, recar...","Wed, 21 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMizgFBV...,"{'href': 'https://www.correpi.org', 'title': '..."
36,"Gatillo fácil: quién era Víctor Vargas, el hom...","Gatillo fácil: quién era Víctor Vargas, el hom...","Fri, 02 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMi0gFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
37,Quién era el hombre que murió tras un enfrenta...,Quién era el hombre que murió tras un enfrenta...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi5wFBV...,"{'href': 'https://www.infobae.com', 'title': '..."
38,Denuncian un segundo caso de gatillo fácil en ...,Denuncian un segundo caso de gatillo fácil en ...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMihgFBV...,"{'href': 'https://cenital.com', 'title': 'Ceni..."
39,La autopsia confirmó que la policía mató al ve...,La autopsia confirmó que la policía mató al ve...,"Thu, 01 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMimwFBV...,"{'href': 'https://www.diarionorte.com', 'title..."
40,VICTORIA DARRAIDOU: “ERA UNA MUERTE ABSOLUTAME...,VICTORIA DARRAIDOU: “ERA UNA MUERTE ABSOLUTAME...,"Mon, 29 Dec 2025 12:33:18 GMT",https://news.google.com/rss/articles/CBMiZkFVX...,"{'href': 'https://provinciaradio.com.ar', 'tit..."
41,Debatirán proyecto para que una plaza de Lugan...,Debatirán proyecto para que una plaza de Lugan...,"Wed, 08 Dec 2021 08:00:00 GMT",https://news.google.com/rss/articles/CBMi6wFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
42,"Lugano: basta de gatillo fácil, justicia por N...","Lugano: basta de gatillo fácil, justicia por N...","Tue, 28 Nov 2017 08:00:00 GMT",https://news.google.com/rss/articles/CBMiqwFBV...,"{'href': 'https://prensaobrera.com', 'title': ..."
43,Villa Lugano: solicitan la indagatoria a tres ...,Villa Lugano: solicitan la indagatoria a tres ...,"Thu, 18 May 2017 07:00:00 GMT",https://news.google.com/rss/articles/CBMizwFBV...,{'href': 'https://www.agenciapacourondo.com.ar...
44,Sociedad :: El Percha ya no aterroriza a Villa...,Sociedad :: El Percha ya no aterroriza a Villa...,"Thu, 20 Jul 2006 07:00:00 GMT",https://news.google.com/rss/articles/CBMidkFVX...,"{'href': 'https://www.pagina12.com.ar', 'title..."

In [27]:
# google_news.period = '7d'  # News from last 7 days
# google_news.max_results = 100  # number of responses across a keyword
gn.country = 'AR'  # News from a specific country 
gn.language = 'es'  # News in a specific language
# google_news.exclude_websites = ['zerodha.com', 'bbc.com']  # Exclude news from specific website i.e Yahoo.com and CNN.com
gn.start_date = (2025, 12, 25) # Search from 1st Jan 2026
gn.end_date = (2025, 12, 29) # Search until 1st March 2026
# google_news.end_date = (2026, 1, 2)

articles= gn.get_news('Gatillo')
len(articles)

22

In [28]:
df = pd.DataFrame(articles)
df

,title,description,published date,url,publisher
0,Denuncian un nuevo caso de gatillo fácil en la...,Denuncian un nuevo caso de gatillo fácil en la...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMimAFBV...,"{'href': 'https://www.pagina12.com.ar', 'title..."
1,Caso de gatillo fácil en Lugano: un hombre mur...,Caso de gatillo fácil en Lugano: un hombre mur...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi6wFBV...,"{'href': 'https://www.filo.news', 'title': 'fi..."
2,Gatillo fácil en Navidad en Villa Lugano: crec...,Gatillo fácil en Navidad en Villa Lugano: crec...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMizAFBV...,{'href': 'https://www.agenciapacourondo.com.ar...
3,Investigan un posible caso de gatillo fácil en...,Investigan un posible caso de gatillo fácil en...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMitgFBV...,"{'href': 'https://www.perfil.com', 'title': 'P..."
4,Denuncian un segundo caso de gatillo fácil en ...,Denuncian un segundo caso de gatillo fácil en ...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMihgFBV...,"{'href': 'https://cenital.com', 'title': 'Ceni..."
5,Navidad Trágica en Villa Lugano: la pobreza y ...,Navidad Trágica en Villa Lugano: la pobreza y ...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,"{'href': 'https://radiografica.org.ar', 'title..."
6,La reconstrucción de Mapa de la Policía que ex...,La reconstrucción de Mapa de la Policía que ex...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi0wFBV...,"{'href': 'https://www.eldiarioar.com', 'title'..."
7,Otro fusilamiento de la Policía de Macri a ple...,Otro fusilamiento de la Policía de Macri a ple...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMimgFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
8,El asesinato de Gabriel González confirma a la...,El asesinato de Gabriel González confirma a la...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMitwFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
9,"Gatillo fácil en Caba: según la autopsia, Juan...","Gatillo fácil en Caba: según la autopsia, Juan...","Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiswFBV...,"{'href': 'https://elciudadanoweb.com', 'title'..."
10,Pelea entre vecinos en Villa Lugano: intervino...,Pelea entre vecinos en Villa Lugano: intervino...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMinAFBV...,"{'href': 'https://www.clarin.com', 'title': 'C..."
11,Navidad trágica y gatillo fácil: la Policía de...,Navidad trágica y gatillo fácil: la Policía de...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMizgFBV...,"{'href': 'https://www.pagina12.com.ar', 'title..."
12,Mejor build de Gatillo en Zenless Zone Zero: A...,Mejor build de Gatillo en Zenless Zone Zero: A...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMilwFBV...,"{'href': 'https://vandal.elespanol.com', 'titl..."
13,Gatillo fácil en Lugano: Magnetto y Clarín int...,Gatillo fácil en Lugano: Magnetto y Clarín int...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiogFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
14,Fuertes imágenes: la policía fusiló a un vecin...,Fuertes imágenes: la policía fusiló a un vecin...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMigwJBV...,"{'href': 'https://www.diarioregistrado.com', '..."
15,"Gatillo fácil en Lugano: familiares, organizac...","Gatillo fácil en Lugano: familiares, organizac...","Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMixAFBV...,"{'href': 'https://www.pagina12.com.ar', 'title..."
16,"""Fue asesinado a quemarropa"": la historia del ...","""Fue asesinado a quemarropa"": la historia del ...","Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiyAFBV...,"{'href': 'https://www.eldiarioar.com', 'title'..."
17,Villa Lugano: la víctima murió por un disparo ...,Villa Lugano: la víctima murió por un disparo ...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMirwFBV...,"{'href': 'https://www.clarin.com', 'title': 'C..."
18,La Policía de Macri fusiló a un vecino en plen...,La Policía de Macri fusiló a un vecino en plen...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMivgFBV...,"{'href': 'https://www.laizquierdadiario.com', ..."
19,Investigan la muerte de un hombre durante un o...,Investigan la muerte de un hombre durante un o...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiuwFBV...,"{'href': 'https://www.perfil.com', 'title': 'P..."
20,Constitución: la Policía de la Ciudad le dispa...,Constitución: la Policía de la Ciudad le dispa...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMizAFBV...,{'href': 'https://www.agenciapacourondo.com.ar...
21,Breve historia de una fuerza manchada con sang...,Breve historia de una fuerza manchada con sang...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiekFVX...,"{'href': 'https://www.tiempoar.com.ar', 'title..."

El Destape no aparece en las búsquedas.

In [32]:
publisher_cols = pd.json_normalize(df['publisher'])
publisher_cols

                                    href                title
0            https://www.pagina12.com.ar            Página|12
1                  https://www.filo.news            filo.news
2   https://www.agenciapacourondo.com.ar  Agencia Paco Urondo
3                 https://www.perfil.com               Perfil
4                    https://cenital.com              Cenital
5            https://radiografica.org.ar        Radio Gráfica
6             https://www.eldiarioar.com       elDiarioAR.com
7      https://www.laizquierdadiario.com  La Izquierda Diario
8            https://www.tiempoar.com.ar     Tiempo Argentino
9             https://elciudadanoweb.com   elciudadanoweb.com
10                https://www.clarin.com           Clarin.com
11           https://www.pagina12.com.ar            Página|12
12          https://vandal.elespanol.com               Vandal
13     https://www.laizquierdadiario.com  La Izquierda Diario
14      https://www.diarioregistrado.com    Diario Registrado
15           https://www.pagina12.com.ar            Página|12
16            https://www.eldiarioar.com       elDiarioAR.com
17                https://www.clarin.com           Clarin.com
18     https://www.laizquierdadiario.com  La Izquierda Diario
19                https://www.perfil.com               Perfil
20  https://www.agenciapacourondo.com.ar  Agencia Paco Urondo
21           https://www.tiempoar.com.ar     Tiempo Argentino

EL DESTAPE NO APARECE

In [39]:
# site_name = 'https://www.eldestapeweb.com'
# articles = gn.get_news_by_site(site_name)
articles = gn.get_news('correpi')
df2 = pd.DataFrame(articles)
df2

,title,description,published date,url,publisher
0,A González lo balearon en el tórax y el abdome...,A González lo balearon en el tórax y el abdome...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMikAFBV...,"{'href': 'https://www.pagina12.com.ar', 'title..."
1,Caso de gatillo fácil en Lugano: un hombre mur...,Caso de gatillo fácil en Lugano: un hombre mur...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi6wFBV...,"{'href': 'https://www.filo.news', 'title': 'fi..."
2,La autopsia confirmó que a Gabriel González lo...,La autopsia confirmó que a Gabriel González lo...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiqwFBV...,"{'href': 'https://anccom.sociales.uba.ar', 'ti..."
3,Navidad Trágica en Villa Lugano: la pobreza y ...,Navidad Trágica en Villa Lugano: la pobreza y ...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,"{'href': 'https://radiografica.org.ar', 'title..."
4,Constitución: la Policía de la Ciudad le dispa...,Constitución: la Policía de la Ciudad le dispa...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMizAFBV...,{'href': 'https://www.agenciapacourondo.com.ar...
5,Breve historia de una fuerza manchada con sang...,Breve historia de una fuerza manchada con sang...,"Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiekFVX...,"{'href': 'https://www.tiempoar.com.ar', 'title..."
6,Investigan la muerte de un hombre durante un o...,Investigan la muerte de un hombre durante un o...,"Fri, 26 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiuwFBV...,"{'href': 'https://www.perfil.com', 'title': 'p..."
7,Denuncian un segundo caso de gatillo fácil en ...,Denuncian un segundo caso de gatillo fácil en ...,"Mon, 29 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMihgFBV...,"{'href': 'https://cenital.com', 'title': 'Ceni..."
8,"Gatillo fácil en Caba: según la autopsia, Juan...","Gatillo fácil en Caba: según la autopsia, Juan...","Sat, 27 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiswFBV...,"{'href': 'https://elciudadanoweb.com', 'title'..."
9,El asesinato de Gabriel González confirma a la...,El asesinato de Gabriel González confirma a la...,"Sun, 28 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMitwFBV...,"{'href': 'https://www.tiempoar.com.ar', 'title..."

Refresh

In [40]:
gn = GNews()
gn.language = 'es'  # News in a specific language

In [43]:
# site_name = 'https://www.eldestapeweb.com'
# articles = gn.get_news_by_site(site_name)
articles = gn.get_news('Lugano Destape')
df2 = pd.DataFrame(articles)
df2

,title,description,published date,url,publisher
0,Cortes y desvíos al tránsito en Villa Lugano: ...,Cortes y desvíos al tránsito en Villa Lugano: ...,"Mon, 10 Aug 2026 21:12:42 GMT",https://news.google.com/rss/articles/CBMiwAFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
1,El palazo de Diego Lugano a Bielsa tras la eli...,El palazo de Diego Lugano a Bielsa tras la eli...,"Sat, 27 Jun 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiwgFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
2,Un histórico de Uruguay chicaneó a Messi por l...,Un histórico de Uruguay chicaneó a Messi por l...,"Tue, 02 Jun 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
3,Gastón Edul se la pudrió a un histórico de la ...,Gastón Edul se la pudrió a un histórico de la ...,"Fri, 05 Jun 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMixgFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
4,Bullrich y Pilar Ramírez se mostrarán este vie...,Bullrich y Pilar Ramírez se mostrarán este vie...,"Thu, 07 May 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMi1wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
5,Encontraron a la adolescente de 15 años que ha...,Encontraron a la adolescente de 15 años que ha...,"Sat, 04 Jul 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiygFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
6,Beneficiará a más de 200.000 personas: la auto...,Beneficiará a más de 200.000 personas: la auto...,"Thu, 11 Jun 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
7,Grave accidente en la Avenida General Paz: och...,Grave accidente en la Avenida General Paz: och...,"Sun, 08 Feb 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMi6gFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
8,La obra en Villa Lugano que mejorará la frecue...,La obra en Villa Lugano que mejorará la frecue...,"Thu, 16 Oct 2025 07:00:00 GMT",https://news.google.com/rss/articles/CBMivwFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
9,No es el monorriel: Jorge Macri confirmó un nu...,No es el monorriel: Jorge Macri confirmó un nu...,"Fri, 12 Dec 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi1wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
10,Cambian los recorridos de dos líneas de colect...,Cambian los recorridos de dos líneas de colect...,"Mon, 24 Nov 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMi2wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
11,Autopista Dellepiane: cierran para siempre una...,Autopista Dellepiane: cierran para siempre una...,"Mon, 15 Sep 2025 07:00:00 GMT",https://news.google.com/rss/articles/CBMizAFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
12,Chau línea 23: qué va a pasar con el recorrido...,Chau línea 23: qué va a pasar con el recorrido...,"Thu, 13 Nov 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMiwgFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
13,Bielsa cruzó a Diego Lugano por su frase sobre...,Bielsa cruzó a Diego Lugano por su frase sobre...,"Wed, 17 May 2023 07:00:00 GMT",https://news.google.com/rss/articles/CBMi1gFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
14,Agüero destrozó de la peor manera a Lugano por...,Agüero destrozó de la peor manera a Lugano por...,"Thu, 18 May 2023 07:00:00 GMT",https://news.google.com/rss/articles/CBMi2AFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
15,El barrio porteño con construcciones que parec...,El barrio porteño con construcciones que parec...,"Thu, 08 May 2025 07:00:00 GMT",https://news.google.com/rss/articles/CBMi5wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
16,Repudian pintadas negacionistas en escuela de ...,Repudian pintadas negacionistas en escuela de ...,"Fri, 06 Oct 2023 07:00:00 GMT",https://news.google.com/rss/articles/CBMi2AFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
17,Reorganización en el AMBA: el Gobierno podrá f...,Reorganización en el AMBA: el Gobierno podrá f...,"Wed, 12 Aug 2026 22:04:14 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
18,"Batalla campal con palos, piedras y amenazas t...","Batalla campal con palos, piedras y amenazas t...","Tue, 26 Sep 2023 07:00:00 GMT",https://news.google.com/rss/articles/CBMi9wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
19,La venganza de Di María y Paredes contra el ur...,La venganza de Di María y Paredes contra el ur...,"Tue, 16 May 2023 07:00:00 GMT",https://news.google.com/rss/articles/CBMi5AFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
20,Furor con el primer gran cine en el sur de la ...,Furor con el primer gran cine en el sur de la ...,"Tue, 04 Aug 2026 19:50:06 GMT",https://news.google.com/rss/articles/CBMitwFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
21,Avanzan las obras en Parque Centenario: cómo q...,Avanzan las obras en Parque Centenario: cómo q...,"Tue, 11 Aug 2026 22:35:13 GMT",https://news.google.com/rss/articles/CBMipAFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
22,La Asociación Uruguaya castigó a sus jugadores...,La Asociación Uruguaya castigó a sus jugadores...,"Sat, 27 Jun 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiwgFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
23,Qué reveló la autopsia de la abogada asesinada...,Qué reveló la autopsia de la abogada asesinada...,"Tue, 30 Jun 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiqAFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
24,Papelón de Bullrich: quiso atacar al Gobierno ...,Papelón de Bullrich: quiso atacar al Gobierno ...,"Tue, 18 May 2021 07:00:00 GMT",https://news.google.com/rss/articles/CBMizgFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
25,Cronología del caso M: las últimas noticias - ...,Cronología del caso M: las últimas noticias E...,"Thu, 07 Jul 2022 07:00:00 GMT",https://news.google.com/rss/articles/CBMioAFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
26,La moderna autopista parque que construyen en ...,La moderna autopista parque que construyen en ...,"Thu, 10 Jul 2025 07:00:00 GMT",https://news.google.com/rss/articles/CBMixgFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
27,La Ciudad anunció la construcción de un nuevo ...,La Ciudad anunció la construcción de un nuevo ...,"Mon, 20 Oct 2025 07:00:00 GMT",https://news.google.com/rss/articles/CBMi2AFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
28,Carnaval 2026: lista de corsos en CABA por bar...,Carnaval 2026: lista de corsos en CABA por bar...,"Tue, 10 Feb 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMi2wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
29,Explotaron los memes contra Viviana Canosa tra...,Explotaron los memes contra Viviana Canosa tra...,"Wed, 17 Mar 2021 07:00:00 GMT",https://news.google.com/rss/articles/CBMiyAFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
30,Día del trabajador en CABA: cómo funcionarán e...,Día del trabajador en CABA: cómo funcionarán e...,"Fri, 01 May 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMi1wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
31,Un histórico colectivo que une a la Ciudad de ...,Un histórico colectivo que une a la Ciudad de ...,"Tue, 25 Nov 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMijAJBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
32,"Tras el temporal, rescataron a un hombre que l...","Tras el temporal, rescataron a un hombre que l...","Tue, 17 Mar 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMi1AFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
33,Corte y desvíos en la Autopista Dellepiane: cu...,Corte y desvíos en la Autopista Dellepiane: cu...,"Fri, 01 May 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiygFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
34,La fiscalía pidió que se suspenda el juicio al...,La fiscalía pidió que se suspenda el juicio al...,"Thu, 16 Feb 2023 08:00:00 GMT",https://news.google.com/rss/articles/CBMi8AFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
35,SILENCIO LETAL: las especies venenosas que VIV...,SILENCIO LETAL: las especies venenosas que VIV...,"Tue, 14 Jan 2025 08:00:00 GMT",https://news.google.com/rss/articles/CBMixwFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
36,Papelón de de TN y Majul en LN+: quisieron ens...,Papelón de de TN y Majul en LN+: quisieron ens...,"Thu, 13 Jul 2023 07:00:00 GMT",https://news.google.com/rss/articles/CBMi6AFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
37,La insólita cumbia 420 dedicada a El Pelado Tr...,La insólita cumbia 420 dedicada a El Pelado Tr...,"Thu, 05 Jan 2023 08:00:00 GMT",https://news.google.com/rss/articles/CBMiuwFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
38,Dolor en el fútbol argentino: la inesperada mu...,Dolor en el fútbol argentino: la inesperada mu...,"Fri, 19 May 2023 07:00:00 GMT",https://news.google.com/rss/articles/CBMi2gFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
39,Rescataron a un zorro que apareció en las inme...,Rescataron a un zorro que apareció en las inme...,"Fri, 26 Aug 2022 07:00:00 GMT",https://news.google.com/rss/articles/CBMi5wFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
40,El día en que murió Cristian: así fueron las ú...,El día en que murió Cristian: así fueron las ú...,"Wed, 01 Mar 2023 08:00:00 GMT",https://news.google.com/rss/articles/CBMi5gFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
41,"""Fue un solo día"": la indignante respuesta de ...","""Fue un solo día"": la indignante respuesta de ...","Mon, 29 Mar 2021 07:00:00 GMT",https://news.google.com/rss/articles/CBMiiwJBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."
42,El destape de Nela Lugano en su luna de miel -...,El destape de Nela Lugano en su luna de miel ...,"Tue, 16 Apr 2019 07:00:00 GMT",https://news.google.com/rss/articles/CBMiqAFBV...,"{'href': 'https://www.caras.uy', 'title': 'car..."
43,"""No le daban pelota"": la grave acusación de la...","""No le daban pelota"": la grave acusación de la...","Tue, 10 Nov 2020 08:00:00 GMT",https://news.google.com/rss/articles/CBMivAFBV...,"{'href': 'https://www.eldestapeweb.com', 'titl..."

In [25]:
# site_name = 'https://www.letrap.com.ar'
# site_name = 'https://pagina12.com.ar'
# site_name = 'https://lanacion.com.ar'
site_name = 'https://www.eldestapeweb.com'
news = gn.get_news_by_site(site_name)

In [26]:
news

[{'title': 'Patricia Sosa, 70 años: "Fue muy fuerte lo que nos pasó con Oscar" - El Destape',
  'description': 'Patricia Sosa, 70 años: "Fue muy fuerte lo que nos pasó con Oscar"  El Destape',
  'published date': 'Wed, 12 Aug 2026 19:04:12 GMT',
  'url': 'https://news.google.com/rss/articles/CBMingFBVV95cUxOdUpBT3VaZGJzN3pFZnA5OENNUDFUeTI2MXhGd1pMelJTZTlIaUdVT3BvcE1yV3RRTEUwVEptTDRXY1RrOVNkajBrRFQ5YXFTdS1zN1NHa29YUTVQOTBIZklNWncwV1lET0o1a0w5NEhFLTA3djF2M2J5MkJxdUVBLUp0YVpTVUo1OHRzYjlUN1dRODdDc20tdXJkLUNGZ9IBsgFBVV95cUxPMjk4c2ZxOHFCYXMxaWlvY3dTRExoZmFIa2hoS29mMl9DRkMwZ1RhdTAxQUdpTFBsWWV0M3pjRmxYREU0SHBXaEItYXBCQmdQQWxPaDdkLXEzWWRsYjV5U2dwajkyZmRaWE95RnFLZnBPN1VSXzN4ZDFfSmRxdkQyWkRDX05Jc2VDZzFQRDlwUm1NZzdUYjdkU0Vfd3hiSV9GaUFGaVJJNExlUGdRQnZwSDd3?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Casos en aumento: el virus respiratorio que preocupa y pone en riesgo a niños - El Destape',
  'description': 'Casos en aumento: el virus respiratorio que preocupa y pone en riesgo a niños  El Destape',
  'published date': 'Wed, 12 Aug 2026 13:34:54 GMT',
  'url': 'https://news.google.com/rss/articles/CBMisAFBVV95cUxQVXJLZzJzZmw2TTZBVVVRZGk0SXoyQmV5S1FJb0lKZFdfM2tTWVV2Q3Nta01BTWV0WGdlLW1FVnFDZEVCMjkxc1g3QnR6Z0xmZEE3cENqOUN4am1aZ0hVWUtLa01yWm1DTkFXd25KYVFLc0pvTnRfWExWRDNsUlVkbmFZTVpvWnkwbVVkZGVMWHZsUjF5WktPajI5WFItMVhrc2J0UUJ6dlVNMmhta1dEd9IBxAFBVV95cUxPQzRsWjBEOG1PSG5rOTZDLXpvRjVSZl91TzZsVFY2dlVaRnBycHMtR1VZX25fMmtJcGgtWDI0TkprTllvOHF1eDVuYUlPZ0ZrZTdveUM5ZEhsTjdyRS1iQjVPTnItNnE2bDZBd1ZQRzhROU1yU1FVZ0hJRmRjcFZUNEJuWjNhLWhhN3lEWlJiSDVEWldwUkJNb1pUaU1ZOTZFRzVnZUMxYUpWOElncTJVUFJ3QlNJckhENzhSSDF5eW1zenFM?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'CON POGGI al MANDO, en SAN LUIS TRES de cada CUATRO HOGARES RECORTAN en COMIDA - El Destape',
  'description': 'CON POGGI al MANDO, en SAN LUIS TRES de cada CUATRO HOGARES RECORTAN en COMIDA  El Destape',
  'published date': 'Tue, 11 Aug 2026 18:14:29 GMT',
  'url': 'https://news.google.com/rss/articles/CBMi1wFBVV95cUxOUDJLb3NDX2ZvV0JmajNSTU1tTGxfbV9WQTc0VmI3djV5clhCUmMzV1VRcE9fazRqdDlrdVRpSEZQQ3hPaVVZQkJLaldjZmY3aU90ckJtMldBS1pQOVZ0NzBRZUh4OTN4OTNGdmF3b0lFVlZOWVlld29Ubzh1M1JVUVFFTE9pbENia09WczdobGpDbVRyUHlZMC1VUGNUc1N6V29JeDVieURISUQxN0c3aldOQmFUX3UzZFVmbC1qcTY0ZVFPWVZmbWN5TlJXZWkwRVg0M3EyY9IB6wFBVV95cUxOajhxVS12Y0hnd2JFX0lCaTctWmlpMmVLN2hvcjRoenQzQXU0MU9qOExuVkllbURrdmxrRERZUmYxZUtWRVVCUFdRbVJsQU42c0Izb0hnVVdIWkJ6NG1USVNlQzBXREhLaVE4R2plekhjZnBwOE5jVmh2Yk9XUnFHZWwxdnZwUGMxTkhYOW5lcHc1VEtRc3F2emxrVDNYZk1neXR5d3FNU2NpaUg3MUwwMU9KeVlLeGlLRVZXRUFidDJRY2szSzRIbDJtZGoxVF9sTk9NQTEzTXA2dG9SOGlibnpNcWhjTkNMUHNz?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Ley de Tierras de Milei: quiénes son los senadores que votarán a favor de la extranjerización de la tierra - El Destape',
  'description': 'Ley de Tierras de Milei: quiénes son los senadores que votarán a favor de la extranjerización de la tierra  El Destape',
  'published date': 'Fri, 31 Jul 2026 07:00:00 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiqAFBVV95cUxPUTMwQlVuRDRVUlZiYTJXUElBTUM3RTlPR3dQYjZTeTN6QVRpMU1qYnRpNnJkandDM1kwTE9WMEM2UXpSTUU0WXNtcjltY3ZVUHpRaTRCV3ZyWmtaN2RIUUtLY0VqZGJKZnFqR2xZRjZWLUxaNkpwTHZsSC1WUVhQblQyOEdCTHhqNDlfblFsalZKYTRPRmJYa1RkRzRRQmhxZ1BLVmJOZmPSAbwBQVVfeXFMTnRLRTVVa2N2M2NTXzdHMHRodE1mM3E2NmUxRW1sY0ZhV3cwa2trRXJ1czhZNWllMERyT2FfelhmYTlmd1k1YzVIT3VyYjNjTEtYY00xTVVHV0FTcGxnUjJEcVFRRDZVa0xGUzVDX19TRWE5MHFiTzhVTG9haVk5QS1MSkZ4ajdDdUxGbUV1akoxR0kzcFJaQUw3d1dSOU13SkFHWDhMVEl0c1NGSlN0WHJPamJINHJJaUlGTHA?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': '"Un industricidio": Quintela volvió a cargar contra Milei por su modelo económico - El Destape',
  'description': '"Un industricidio": Quintela volvió a cargar contra Milei por su modelo económico  El Destape',
  'published date': 'Thu, 13 Aug 2026 02:15:00 GMT',
  'url': 'https://news.google.com/rss/articles/CBMi5wFBVV95cUxPdXczaVllT0pFb2s0a1hsbDFBc2JqUndHeHpVMTVMUHdlcFdoOG1mSEc3cmY0YTFKaERrMWJ5UkJOZmxNSGVwNnlCaVR2aGtoMTd5ZHU1OGZFR191LTYzZzhfbzd0UEdiSk5JU3BoYXN6OExGZ28wRHJfQkZjd0JZbm5ZQWRjUzJraTY4VUdOZzhEa2t4UE5wYzFUbnR3NHBsSnFSYmJhU21sUUlVNWwtSkxpRFF2MUlQV3VCRk9hNjQ3OTNsNVZreFkzRkRsbnFWaGZmbGVBdmJVV0pDRzZ6dE5SaUtzUnPSAfsBQVVfeXFMTjAyYjNNZWF2SUhHNmt3RGxqYTZ0aTJ4WENmdGZHYk55cV8tUS1pSHNtY1E3WWtrQ2VUSTExOURQVzB1Qkt6Z2paQTBHcFV4RW9DdXFKa255b1lFZWRzYXAzQ09OZl9UOUdTVDZFdE42LTRBZUE2VlQ5UWhaNC0yNENPZG1qNDlWWGE2Mlg1YXliNmlveWJJS1VuRHVqel9xbHVlZlg1eEk5Q3ktVTJBZEJxeWYybzFtRWFXb2pMLWxtcXk1Y2UzUkxSeHRJQjF1VzhXUmJBYjVrMERTWXA1VzU0QkhWaGVGWUpVZGFJOF8tU2wxYUUyX0hNOGc?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Luego del traspié en el Senado, al Gobierno se le complica eliminar las PASO - El Destape',
  'description': 'Luego del traspié en el Senado, al Gobierno se le complica eliminar las PASO  El Destape',
  'published date': 'Wed, 12 Aug 2026 06:59:35 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiqAFBVV95cUxNOUlLZTJhRWJtXzREOW4wNExEeGdMaXVlMVd1SjA1V2xrZl9MV2pBYjFvUzh2UzdIbWJxSktSVnQtY01ubXB6MTZHYk8wY3l6Z0JoT3dlRVdnWnpIRy1WU0RmbXI1T2dxRWFsdXZnQmFpeE5GN3ZFVVo2WHBiOVBnbWdVZ1ljb0Q4V21xeTR0cFhjX2ZwZ1l4RkhwQVhHSlpENWdPdGpaWjTSAbwBQVVfeXFMTkZ5RlN6SlVDLTFvekhnQkdZX2xkbWVqeGgyb3dpbWJ1MHp5NFNROWQzWm1iNnJRelBVRGwzZ2JYaF9lUlJmQlRHUjNxNXF2bUdaS19LLVFtdlhROFpoY0FzSXN0TV9VY19zRlVpdnRFajNaUHEyRmNadWlsaGFEd0QwVEc1U3hWLUE2V0kxZ0ZfaHJ6WUZuTzJuMUVfT0FyTjUyanphZlRTVThkNS1jcnFGWmV1bGFveFdSa2M?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Exclusivo: el nombre de la empresa elegida por Magnetto y la llave para el pacto Clarín-Milei - El Destape',
  'description': 'Exclusivo: el nombre de la empresa elegida por Magnetto y la llave para el pacto Clarín-Milei  El Destape',
  'published date': 'Wed, 12 Aug 2026 02:13:31 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiqgFBVV95cUxQR1RBdnQ2ZUY1RGt0TE9LVDdXY3JVaVlDcmtDNmlVcEpxX1J5WU9sczJ5ekxYcjZJR3duN0VpVS1nZDlPYmZWN0dsQ2JVRlFCTzIzeWtNWld5bGd4S0JObWdJTU8xcmtBcnVsbFlPemhldUlybElPcnhjdjF6QTkzV1docFhUellSOEFLVkdoY3V2YktSOG9JQUF2UGlOdXhMSUZ4R2RtdzJvd9IBvgFBVV95cUxOUG9xMFg0c2E3c3BvandlSTVDM01yX29TX25MdnBlbWdTRTY0SFpnR19pc2t2SnBLd1lqV04yeF9NbDBKdUVEUF9mT2VDa0hyZUpZSUV2UVFDLVExWE9Cd2Vfck5yWHZhWk5uUlctU1RDZ2VMOGJmMmJ4a2ptQS1vUzRrZnVLcFlpWWRaNndObUJ6Ti1HNjAzbVlHcnBGanlvOHNNTms0bERzUW1vSUlYZUNreEkxdnpKY2lqY3BB?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Ualá, la peor de todas: pérdidas por 804,3 millones de dólares y una fuerte crisis de morosidad - El Destape',
  'description': 'Ualá, la peor de todas: pérdidas por 804,3 millones de dólares y una fuerte crisis de morosidad  El Destape',
  'published date': 'Wed, 12 Aug 2026 02:11:36 GMT',
  'url': 'https://news.google.com/rss/articles/CBMidEFVX3lxTE9PUXhicFVqSjRidVpRR1BQU0Z1WlhDWWhjSm05SDNKRHVScjNtdlJJd3FWaElpcmFVcFZmRkNnS29jTXR2Z2JuV2JaNmhoTmpJeTI3ZnBvVmZLd2xRQmRkaXNYNS1ZeFI2ZFBQZzJIQVc5U2Zq0gGIAUFVX3lxTE8zUFpYRWhqUXRBUmNGc2NWU2RndDBPUXRmajZucDNUMDZBYVl5elh0d0VfZkg2QzJwMk5WYlFid1Y2a2pfSWlhdmVIWjBtRnkyNFRTWUlFdHZHbkNBeFNYamwtbGRnanRWaEZHd2xUTWx3T0c1T1owN2NWak9BbFF4NFpEN01FQWI?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'El Destape - Sigamos Haciendo Historia - El Destape',
  'description': 'El Destape - Sigamos Haciendo Historia  El Destape',
  'published date': 'Thu, 23 Nov 2017 21:57:10 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiQ0FVX3lxTE1iRlN0T01zeURfLWE5SjYtMGQ1LWxxVExudk1NOTFxTGVCV0dfU1JLRzJuUFBqRVdfTXJUTHRMR2liU1k?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Se jubilan con otra fórmula: el cambio oficial de ANSES para quienes inicien el trámite desde este mes - El Destape',
  'description': 'Se jubilan con otra fórmula: el cambio oficial de ANSES para quienes inicien el trámite desde este mes  El Destape',
  'published date': 'Wed, 12 Aug 2026 18:29:42 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiuwFBVV95cUxOWktpVWM0Rm03c0JWTXRSTGlnVmdyR1VzRFowZ0Z3eFhDN3p5enkxc3Z4eE1VNk10SkRFNjBhaFEyZ2huOVp6MnAzNlRCdmlPSFBVcFowemFROFRCZkUyYTB1Rm16dmdmX0pBWHhMOWxJdVBXenZ1NTJVdDNBRm5xY0lHTTdnSndwS2Fqd1hWTkdGeVNuWUctemZ4UHZHZ1RRS19tMGVlaThCWUpxbGdLLTM3bzZ5SlhleHU00gHPAUFVX3lxTE5jVjRVdlhSZUVUZGRsOElyVEZxSzN6Wkx5bXYxS29rcTB0eWEwME5Ja2JNQzAzMjdmNXlIY0x0WlJGQ3VYenJTRFphMjJQbnZsQnVabkU5MTVVWUFBUi1acVFYVmlUZFRkUTdrMDM3TXEtdDhQNzBOZmVyVjI3b3JmQ0FrTjNQMElpQ0RaTm1ielYxUHZqY2RXVGhvbkh4SDhMdC1RdVBRc2gxV0ROOVQzdXo2aS15eklCZjZvZU5yMUUxX0ZIV04yOVJxc1k4QQ?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'El GOBIERNO DE MILEI deja sin SALUD A LOS EXTRANJEROS en Argentina - El Destape',
  'description': 'El GOBIERNO DE MILEI deja sin SALUD A LOS EXTRANJEROS en Argentina  El Destape',
  'published date': 'Tue, 11 Aug 2026 14:08:57 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiwgFBVV95cUxQNEJVNUpLSXE2YU1CbWM4aHVlOFV2dmZjZzNYYTVpZTRISTZfNHFONy1kV3A2OS1mNWY1NHhYT0xHM2FfS2ZSbV9OUTJ1THhtWTFtN29FNm1OR3RxdlBWRjQ1c3BteTNPUUpubWNBOE1VdUMxbkZVZVByRFlSaWdvb1M1VGJTQjkyNmhrWWxIV3kzOFZNOE1qZGNLNEJVR0RxZDJVVG9rQW9JLUlGc1FaYWc1SkRJdmZYX0NNaXZtcWloZ9IB1gFBVV95cUxPaExxRGNGb256aDlyLUFTSktOOGJZMWVoaXpiOU5PZHRTMnJPRjlFbWx5NVlCNlFzb0ZWZWxQQmNmem9ZNDRHWVRBVW5SNGN5c1hSbFN0RXNUbjFfNDRscjJpN3J2RE5JVFJsamU5MXBLeU5WOFM3VWpqWXhYNTRSLVZyalRKdDFfLVhIeHpqc0lkaDJrUUpQSXVvSVZuc3FqYUxFQ2hlR1AyVWNvaVEtS2dySlA4X0hXVlBLSG4xQVBjWGhtS1JZajdzMjlXUkpXdV8xMWRB?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Minería: el Gobierno ELIMINÓ controles CLAVE de monitoreo ambiental - El Destape',
  'description': 'Minería: el Gobierno ELIMINÓ controles CLAVE de monitoreo ambiental  El Destape',
  'published date': 'Wed, 12 Aug 2026 13:15:39 GMT',
  'url': 'https://news.google.com/rss/articles/CBMivAFBVV95cUxQNW5FRy1hRll6YTBjaTdIOWhjcmw4QktBNWx1bDlwbWZWZzEwWmlyNXVPQ2lUN1ZTam1HQ1lhSDZCbVh4enctanRGUGtMXzVFVVhVNDhqWnluMkh3STFFcnVndllidnNIbW1oTjE4Um80TFNEam9tUXZUMnd6V2oxbWF4NlNTM0dKZ01oVUQ0eWlCSjlYbVJrLTJlblkxS2QxSFlybHUxZDY4akwtTDlfX0hILW5UMnVFVXljctIB0AFBVV95cUxQSG5LdXZ4YXZHQjRob0JOTlpLWXFYdUk1YmdPbHFteFFrTEJpb0pqdGlSQzIxcFVUQm1palJzMU1rLTFWNk4yRUI2RW1nUlBFdThnODQ5dkxhN3lYeS1lc3pHal9yLW1XQ3JhWjhaX2NZRTZZdzN1OXRGdmpFdzJSUUtldTZtZmxIWjJHek5IMlpuUUFXbFdrb3RmVW55RHQ5VHFvQ1lOMi05RGNaYnNFa0ZoaEhjMGFGcWRFQVBtcFZXSjVWVENLV1lLNElYcmh1?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Terremoto en Colombia: encontraron con vida a un argentino que estaba desaparecido - El Destape',
  'description': 'Terremoto en Colombia: encontraron con vida a un argentino que estaba desaparecido  El Destape',
  'published date': 'Tue, 11 Aug 2026 21:09:10 GMT',
  'url': 'https://news.google.com/rss/articles/CBMitwFBVV95cUxNNVdhbnMxZlUzbTh2Tk5xUzB5czN3RzBYU3ZFNkdIWEhoR2xRVUNmMzJ2ZF9EdVNxRU9kZnJpbFBKdXJnNVF0R0dETzU0UHIyaEltMmF2TEtDY2R1TXo1aTdvTHF1bWZoU2lDUk1kVmd1MUJJck84b2dKUzVwempKU0VrSVByNUFtNlItMUVhVTl0VWZKSXpFci1PVjR1QnNkdlJaam5xc05aRFdMV3dFcHpNRS1Hc2fSAcsBQVVfeXFMTzNHem0tdFF1d0I0NmRSNEVBMHQ0Y2R4UGhTa3ZQMmJZTmxPSEVyeHRtOTY0cmMzcVhWUXMwV3ZKMVhEQmVyNTU1OV9nekkyc1NYanNDQmdacHU5Z2pYZ0Z0Qk1wcThpbnkwOU52czdoc09uUXFWRDNmUzVvYzRpcmFkcUkwVmJUcERfa2U2bVgxRHkydzNWMGYxYUt5aTZsRnRXX3dpeFh0NFVibWVKYVFCUlNXLWw0S0xzTjBpUEFQaHFldldfNkhscmM?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'El insólito lugar en el que el Pato Galmarini quiere casarse con Moria Casán: "Estoy" - El Destape',
  'description': 'El insólito lugar en el que el Pato Galmarini quiere casarse con Moria Casán: "Estoy"  El Destape',
  'published date': 'Thu, 13 Aug 2026 14:50:20 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiugFBVV95cUxOcTdtRlppcUZzQXZqdWFjUnRva1hxOVZHbUItbVd5QjBvaFZFdjV4Ty1RclRLR00zdVNnazhRdmFtYTVXTFI4bFVpTndRSWo2aXhFcnpxTEctbEF1Sl9iYjVycGtVcnhSV2VNOW5xaTZqdTFBaEFfQ0pZQWVuLXVmRHNHc2NtRGV6X003RkZmZ0txTExfTlhrUndRTmhYTFMxd2o0dTRsaGtGMDliY2J4TUUtRVlORHZSS3fSAc4BQVVfeXFMUHU1RWxGZ2luOGxKbFZfc2oySmVDcTRfM0NCTVoyZldUbFdsd3dhM20xY2ZDaE1sQU9ZZVQzUWQ0d0k4LTNrRFZyN19icDB4bkREUEx4WHI3cUtWU3d4aE9PelZVbnFlTEhxeVRQZGdwSFFjdG1QQkhrSE1CUUtpdDlLNjBqemJFazBDTG02OG43WGJtZElCcVBSbnNvUENQYk5qOTBqYjlSblNKd2tGYXc5dGN6UnhEX0NHMkJQdjJfemlZa1RWS1l6S09ONmc?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Tenía demencia y parkinson: murió un reconocido actor a los 80 años - El Destape',
  'description': 'Tenía demencia y parkinson: murió un reconocido actor a los 80 años  El Destape',
  'published date': 'Thu, 13 Aug 2026 14:31:17 GMT',
  'url': 'https://news.google.com/rss/articles/CBMisAFBVV95cUxNV0o0eHkxYTNCZnE1T3lmVVhxWG1rbFMxLVZoQU5lRDJyMjA2ZVZiaFFDRjZ4SFFFanpFU0NkaXNGTmRaMV9NR0YxdVZtOVpDcGlISWdoZ3FBZDFnblZPNHVxdW5lX1BVSWtKc0MyV2ZrajJDN3d6SktNektyRlFOQXJvNVFoRWdVaW84M0I3c19NcDlMNjlhVDEzbTB3S3BHUGpfOEtscXhndWdzMjE0UdIBxAFBVV95cUxNQ3ZZMlNQbGlNRS1FSHlJVXg3OUY4Mk5ORUlpWTh1Q3hKVW9aZEUwejFZRTlaNjlFVk4tTGhzeFBvREpkcnV0RUt6LXdNZkJrQ1BtcHhLVWNVTklvdnAzX0NOMTloSTVDaEZJdm5pX2lKSUFkcDZHMzhuRXdoWFFGU252OVpVSl93d0dycWhYREVkME94TnVpb1NNbUhacTFHVGpVdVkzMXBpaGJiR0JfTENXY0NvX1BxdlRwTDhLSDhEZnlP?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Estambul acogerá la Supercopa de España de 2027 - El Destape',
  'description': 'Estambul acogerá la Supercopa de España de 2027  El Destape',
  'published date': 'Thu, 13 Aug 2026 13:30:00 GMT',
  'url': 'https://news.google.com/rss/articles/CBMioAFBVV95cUxNblFiSHdnb1RPWlphRUxVS080WjdIYlBOV2ZqMWcwNUQ0RHhjdmpGSmZrYlByQ08yMHFDWnhMWVJCcFlhZkwybzhvT0c2NnA5RU5LZ0R3SVhCWTN1LTdta05pZ1ByWXIxQmxKWVlqNXMySGhFTEtMNzVOYUtXUTNHeEpOeG00emZ3S1o4Ql84TXZMVEdFeUJOdUx2NXpBNngw0gG0AUFVX3lxTFA2ejlOV0hzdkwyV0hVdVJNTWxmaXYwNHRPNE9FWjVRUkxqZWFxbFdrZm5SdkpLM2k1OHFnUzlXLVRJNTVmaDNFMDN6QXJpVHp1NElaeXdGcFNVdElvNWp0cjJNNTEzU1kzT1QzSFpFNHBpSXVfVHh2TUJ1N3FGMWNGNHAzN1p2emlNTDBuc2JFaXI3dTIwX0gzQjFka21CLTg0WDdQVlctM2h3YXl2aVBQQXQ2cw?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Femicidio en Devoto: asesinó a su esposa delante de sus hijos y se intentó fugar - El Destape',
  'description': 'Femicidio en Devoto: asesinó a su esposa delante de sus hijos y se intentó fugar  El Destape',
  'published date': 'Thu, 13 Aug 2026 13:10:09 GMT',
  'url': 'https://news.google.com/rss/articles/CBMirgFBVV95cUxNdlJGdTdMNHZ6SlRpd05IT1RtVVVqSEtfQzFMdnhIakJmODdBb0Q5M2duYUVJOEpQU0pudEswazItcXdGX3NCLUtSMVFOTUtwNFFEYzRvSW9vdkNwc2Jab0RRVVpQdWd0cVR6R2hOcXRiUW8tYXpLbHdFQTZiWU44VVBOMDJKQXFsNjVMZFZwenJxVnlnckREZG9qWm85M1BqTFBRTDJ1UkVKMDlRRlHSAcIBQVVfeXFMTjNKaTZYQzU0dXZaY0RIUGNtSkluQ1U2UzdOQzVreTBvQ0tFZlRlNUt5cVNtNHZHY044VHF2WE13eHFOeGh1MjVtOGI3cjNLQm12WlNMd1gzcTJJWlZrTnBzUG5DaUNvMUs4bVBjTmNCdnZFTXBEbHRqakhqd1A5bGlVZEZGNW5zVkY2TVFwSTd6SEQwNEt3b0M4cHhLZERsNTJ3c1ltWEFEQVV1V0dsbnNPWXpaWUFrUmdKenlXODBtRmc?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Turquía, Pakistán y Arabia Saudita crearán mecanismos políticos y militares en su pacto, dice Ankara - El Destape',
  'description': 'Turquía, Pakistán y Arabia Saudita crearán mecanismos políticos y militares en su pacto, dice Ankara  El Destape',
  'published date': 'Thu, 13 Aug 2026 12:40:15 GMT',
  'url': 'https://news.google.com/rss/articles/CBMi8gFBVV95cUxNRjRQU0JkOS1YdEVuVHdKZDNVUk9sZXA1T1JTX1F1cUdBcXZ3VFhyQ3BRUVJ0QVU1VURaZW82T0N3enRqb19EdEpMTEktQWY1ZlZQUXBVQlR1aW10S21ZcVI5Y3llcVBFT1c2MWM2QmxzTU9IaDdDVldWMHo5bWo2cVpneHA0Nnlxd1QySV9MdXlPTnRjd3ZyVTE5dTI1WGx2bzBDck4zRzRucENDQVBjcVMxdzFremFlbS02N040cTRmaWNVQVowejFzWm1aU2czWEt6VEhBdDBmSUFyaDJGcldTVW84WnlqcDJ5VHJGaXkxd9IBhgJBVV95cUxNYWpxLTZzZG1aYUpna2tSVHluZl91WXQzUlIydkt3eV9VeTI0NmFhWUtzeW1uS2loTlc2UlBmWVpXVThybWhGb1FfRjA2NzNYQlpIVjNWNFoyRnJUQ0JTTW5WMVZ3bmFyN2RmNVBKVVNlMEVjb1R5Ml9QRVB0YkN6Y1lWbHc2R3VSa1BaQVVCbWM5ZVJnamRXRDllUnVaRmpmUDNxdEpOdzFRYzlOSThQQ2hWSGhXVU5EZ0JKaXl2TC1LdTh3QkVDel9sUXcwS3RaYVZfbXlJc2lhZ25mWm9fYUZjdDF1bjJUZ29JVFpPTXJ3Q2J3S2JqTWdLbVFlSjFqVUhEZDRn?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Precio de la nafta en CABA y PBA: a cuánto cotizan los combustibles hoy jueves 13 de agosto - El Destape',
  'description': 'Precio de la nafta en CABA y PBA: a cuánto cotizan los combustibles hoy jueves 13 de agosto  El Destape',
  'published date': 'Thu, 13 Aug 2026 10:44:45 GMT',
  'url': 'https://news.google.com/rss/articles/CBMi1gFBVV95cUxOTUJDclFQUF9ReGtpOWFtVFQ3a3dSRHNWNFAzSHFhSTFrWGdLSXNsQkl1YXJENFRDZkhEdTREWTlUb1ZVSzROMEcwbXppN2Z3VUJfU0NVZWR5eGx5N1BTYnU1b2VoOGRkdkUtYTIyWUFjdF9JNllPQ09DNnlDR0xVYUs4d0kwQVhVVHZsQTM1anYtNGtVZEFvRGRqcTREUktscU9KRnZ2VmZaN29MLWI0VVp1MGZKNmVPVThlZjdYNWtDMDVQcTE4YWlubW9KN3N5ODAxMG530gHqAUFVX3lxTE9RM1FtY1dLYzhQTjFueWZKaERSdlZMRE1DVWVUNzVVNUt3MU02QUE3NkVoaEJSdlpHdlU2b09VOTRSMEQ2ekpYelBaeF9KMXJmM05YX3hWU3gzN0hNZ1V3UXNONDdEOHFsRVBkbjBXalNDb2xieVJiZlEyLVkxcDhvZzE2ZUVMbXVJUEg1QnlLeVlDS1VTYnd5dHNLU0dBU2EzNl9HLTZ1cFd0X0tGU0xCRFpCNjZFRDRpOTZuekRUZWY1cnFLVzVtdVpIbFRNUTFhaUdFb2diSkx5em11eEFBRV9VLTFZLU55dw?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Fechas de cobro ANSES: quiénes cobran hoy jubilaciones, pensiones y AUH este jueves 13 de agosto - El Destape',
  'description': 'Fechas de cobro ANSES: quiénes cobran hoy jubilaciones, pensiones y AUH este jueves 13 de agosto  El Destape',
  'published date': 'Thu, 13 Aug 2026 10:40:24 GMT',
  'url': 'https://news.google.com/rss/articles/CBMi2wFBVV95cUxQblV5OUl5bVpiblZDVGZ5aVBkbVpnSUNDOG12dGFuUDZFajBJc2JwbEpxak9GQ21PbWd4RE1WbmlBWjZBX05rQVR4OGdzNnhmcU0waGFHRHdMQUd3QmJ0TE4tSTI1bGg5djJrcG41VE5hb1FLSERvSUpMaVRPekctT0dTendPcFJrU3NSeU9OQXZReHZBbEVyVUpxczhURExzc2w2LXNYMk5iMktydllicVVCamlkb2oxQmtiNGV1Wmh4LU9vdHp0b2dEUGZGNkhaRE10dUdlZ3hyTVnSAe8BQVVfeXFMTmx3ZTJJRy04c1piZFRBcTlVWTVPT0JuVE9lN092YUZERDNMcXdnRXBVOVNUdGstMUJBaEh5bW1zZnJGUnRuWDQybGYwS0JxQ0JGN1IxLVZGQ2ItVUVLNENfV2QwaDFUdEx0MS1IQ1JKRlQ5X04tRDk2Qm5iX25RenMxVmJ2SHZ5VWI0V2JfVk9TZXV0TzdCU2NraVVqMVJkWnBhdDBaNFNYZElReVJvYkRfZVJXcUtKTThneWZIMVc1a2YwckkzTHhZSDhDUnVaT1RnU1EyQkJTZkZ0RWpEN0RhV1YyRVlITjY3c0dNWGc?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Morena Beltrán elogió a Boca: "Es un equipo avasallante" - El Destape',
  'description': 'Morena Beltrán elogió a Boca: "Es un equipo avasallante"  El Destape',
  'published date': 'Thu, 13 Aug 2026 00:25:08 GMT',
  'url': 'https://news.google.com/rss/articles/CBMiqAFBVV95cUxOTEtrbjdrOUVzd1NKbUFRejRxU2lmaVBsWnRndnpqSG9MYnFkalNnUjZMZnpfM1F4Skc2dWU1aWlSRGZRTWdoMFU4RHRTaU1WNFpnRTlNRWdPX2hqQVlzY3YyZVRFY0xuZ3NKb0dUVDBrVUM4LWJicFRERUpfSFBEVktiVm9UT3RsMnNLNUVrNlUxVlI5a1pkZ1pKQ3pmZ0V6RHctWWFwZjXSAbwBQVVfeXFMUGJiWGw3ZzBVX1IyNVRldnlnazVYTmliOFdiYlFLNXhVd3RmMnk1VlpWOEpHel9JeXF3QjNMWHVoa0pXSmltS0xQSm5JNS0wYWIzd1BwaDBoUHZNaEphNVUyazBNeURnbTVBblNiWWVnYVJJZ25EazdwSTdXeUJ4UE5sbm9oRUlwQTNDODNiMnBzQTRNblBRTlQ5QlA5T3BIRm1RNTEyQXhKZEluY19CWlVCY2lMemtxOEJ5Tkk?oc=5&hl=en-US&gl=US&ceid=US:en',
  'publisher': {'href': 'https://www.eldestapeweb.com',
   'title': 'El Destape'}},
 {'title': 'Inesperado: un famoso relator de ESPN será participante de un reality de canto en El Trece - El Destape',

In [ ]:
keywords = ['Travel & Tourism', 'Climate Change', 'Cryptocurrency']
all_news = []

for kw in keywords:
    news = google_news.get_news(kw)
    for article in news:
        article['keyword'] = kw  # tag with keyword
    all_news.extend(news)

df_keywords = pd.DataFrame(all_news)
df_keywords.head()